title: Sean Barton - Game Developer
email: sean@seanba.com
description: >-
  Hi! My name is Sean Barton. I'm a US-Canadian game developer working in Austin, Texas.
  I've been programming video games professionally since 1999 and I still love it. // fixit - this sucks
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Seanba_
github_username:  Seanba

collections_dir: collections
collections:
  - sidenotes
show_excerpts: true

permalink: /:title:output_ext

emptyArray: []

comments:
  receiver: https://seanba-blog-comments.azurewebsites.net/api/PostComment

authors:
  seanba:
    name: Sean Barton
    email: sean@seanba.com
    url: http://www.seanba.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: seanba
      commenting: open

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

exclude: [tools]

